# Generated by Django 5.2 on 2025-04-15 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_currency'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
